// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUMHKC9eqHTduwKI4_yqWisqz24C1ZhN0',
    appId: '1:607874722810:web:44c022797b96fa1b681243',
    messagingSenderId: '607874722810',
    projectId: 'myapp-a3547',
    authDomain: 'myapp-a3547.firebaseapp.com',
    storageBucket: 'myapp-a3547.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKCecyELVZI15Yo1YvF020l8ghnqFCBEM',
    appId: '1:607874722810:android:9d70648c0e1111f5681243',
    messagingSenderId: '607874722810',
    projectId: 'myapp-a3547',
    storageBucket: 'myapp-a3547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOMv_RmeTQwJYHF3BodViL-k3pLqHl-lk',
    appId: '1:607874722810:ios:d8686968fe4cd7c7681243',
    messagingSenderId: '607874722810',
    projectId: 'myapp-a3547',
    storageBucket: 'myapp-a3547.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOMv_RmeTQwJYHF3BodViL-k3pLqHl-lk',
    appId: '1:607874722810:ios:d8686968fe4cd7c7681243',
    messagingSenderId: '607874722810',
    projectId: 'myapp-a3547',
    storageBucket: 'myapp-a3547.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUMHKC9eqHTduwKI4_yqWisqz24C1ZhN0',
    appId: '1:607874722810:web:83e59ff14ad4f755681243',
    messagingSenderId: '607874722810',
    projectId: 'myapp-a3547',
    authDomain: 'myapp-a3547.firebaseapp.com',
    storageBucket: 'myapp-a3547.firebasestorage.app',
  );
}
